name: CD workflow to NPM publish

on:
  release:
    types: [published]

jobs:
  publish:
    if: "!github.event.release.prerelease"
    uses: ./.github/workflows/w-deploy-npm.yml
    with:
      checkout_ref: ${{ github.event.release.target_commitish }}
      tag_name: ${{ github.event.release.tag_name }}
    secrets:
      NPM: ${{ secrets.NPM_TOKEN }}
      GITHUB: ${{ secrets.GITHUB_TOKEN }}
