name: CD workflow to NPM publish

on:
  release:
    types: [published]

jobs:
  publish:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          git config --global user.name "JeremyDolle"
          git config --global user.email "jeremy.dolle34@gmail.com"
          npm version ${{ github.event.release.tag_name }}
      - run: npm ci --omit=dev --ignore-scripts
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - run: git commit -am "🏷️(version) Update boilerplate to version ${{ github.event.release.tag_name }}"
      - run: git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  publish-candidate:
    if: "github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          git config --global user.name "JeremyDolle"
          git config --global user.email "jeremy.dolle34@gmail.com"
          npm version ${{ github.event.release.tag_name }}
      - run: npm ci --omit=dev --ignore-scripts
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{ github.event.release.tag_name }}
      - run: git commit -am "🏷️(version) Update boilerplate to rc version ${{ github.event.release.tag_name }}"
      - run: git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
