name: CI

on:
  push:
    branches:
    - '*'

jobs:
  install-lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install yarn dependencies
        run: |
          cd template
          yarn install
      - name: Run linters
        run: |
          cd template
          cp _eslintrc.js .eslintrc.js
          yarn lint
      - name: Run tests
        run: |
          cd template
          yarn test
