on:
  workflow_call:

jobs:
  lint:
    name: Run and verify jest tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/w-install-dependencies.yml
      - name: Run tests
        run: |
          cd template
          yarn test
